### ISSUE TITLE
Migrate tests from MSTest to NUnit

### ISSUE THREAD

**Issue by rofr** [DevrexLabs/OrigoDB#20]
There are 25 remaining MSTest unit tests in the project OrigoDB.Test.MSTest. Rewrite and move to the NUnit project.

**Comment by vfabregat** [comment]
Maybe I can help with that. But first a few questions:
* There are a Contribution guide? Or just I have to modify the dev branch and send the pull request?
* Why NUnit and not XUnit, XUnit have a better visual studio integration without installing any plugin (Just a nuget package)

**Comment by rofr** [comment]
That would be great!

There are no written contribution guidelines at the moment, a pull request on the dev branch would be fine.

XUnit looks nice, but there are already hundreds of NUnit tests. Not sure if we would add any value by switching. I've heard xUnit is better at testing async code which could prove useful in the near future. What's your opinion?

The goals of migrating are to support cross platform development, reduce dependency on VS and reduce the total number of dependencies.

**Comment by vfabregat** [comment]
Ok, so I'll work on that.

About XUnit just was a curious question. I can't see any added value to move to XUnit. I like because I don't have to install any addon to run the tests. Is possible just installing a nuget package.

About the goals, XUnit works with aspnet 5 (vNext). But the number of dependecies are greater than NUnit. To work with NUnit you only need the NUnit package to work with XUnit you need the following packages:
* xunit
* xunit.abstractions
* xunit.assert
* xunit.core
* xunit.extensibility.core 
* xunit.runner.visualstudio

[here](http://stackoverflow.com/a/957933/1322417) there a nice anwers in Stackoverflow, that could give us more information.

Anyway, NUnit is a great framework and it's, in my opion, a perfect choice.

**Comment by rofr** [comment]
I'm not as concerned about build dependencies as runtime dependencies. OrigoDB has no external deps besides the NET Framework itself.

**Comment by rofr** [comment]
Thanks again for the contribution! What's next? Are you interested in more work?

**Comment by vfabregat** [comment]
You're welcome. Yeah! do you have any recommended issue to work on?

**Comment by rofr** [comment]
Nice! There are a few up for grabs.. and lots of other ideas which I have on a private Trello board at the moment. I'll try to add some more up-for-grabs issues!

Most tasks will need an understanding of OrigoDB from a user perspective. Have you tried it out yet? Start with example repos and documentation at http://origodb.com. http://geekstream.devrexlabs.com is a complete working example. I have some example repos on my personal github account as well.

Maybe you could rewrite your kangaroo time app to use an origodb backend instead of mongodb? That would serve as a nice example for the community and get you familiar with the concepts.

We can chat on gitter: https://gitter.im/DevrexLabs/OrigoDB
